### ISSUE TITLE
Test API call for besttime.app

### ISSUE THREAD

**Issue by Tommygithubaccount123** [ucsb-cs184-f24/team05-GymFlow#13]
Test API call on rec cen. See how much free queries we can get

**Comment by andyjin1** [comment]
API key works and take one credit each. Each account gets 1000 free query credits and each api call uses one credit. 

![Image](https://github.com/user-attachments/assets/406c3c5e-f80f-4c71-960e-a938712a6efc)

We just have decide which ones to use because credits are limited.
