### ISSUE TITLE
Research: How to get gym data

### ISSUE THREAD

**Issue by Tommygithubaccount123** [ucsb-cs184-f24/team05-GymFlow#9]
How do we get gym busy level. Email rec cen IT or find other ways to get data

[support@developer.ucsb.edu](mailto:support@developer.ucsb.edu)
https://developer.ucsb.edu/apis/all

**Comment by Tommygithubaccount123** [comment]
I emailed [support@developer.ucsb.edu](mailto:support@developer.ucsb.edu)

**Comment by Tommygithubaccount123** [comment]
![Image](https://github.com/user-attachments/assets/36dff63f-e2e9-449b-b005-60e706bdf753)

**Comment by Tommygithubaccount123** [comment]
https://github.com/m-wrzr/populartimes
https://outscraper.com/places-api-popular-times/

**Comment by andyjin1** [comment]
https://besttime.app/api/v1/query/details?venue_id=ven_5965782d62435251644858524159365f51575f357263394a496843&api_key_public=pub_e9125578915344d483b13f706007c020

![Image](https://github.com/user-attachments/assets/880c0b95-922b-49c7-a6b8-0555ce1e6084)

BestTime.app is a foot traffic data (API) service that forecasts how busy a public business (venues) will be at any given hour of the week. The data is provided for 150+ countries using anonymous phone signals, and is available for retail, restaurants, bars, gyms, museums, and more.

besttime.app tracks the business of places and provides a complete set of APIs for all the information.
